# Generated by Django 4.2 on 2025-07-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(db_column='ID_Evento', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=255)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, db_column='Fecha_Inicio', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, db_column='Fecha_Fin', null=True)),
                ('ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'evento',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(db_column='ID_Usuario')),
                ('evento_id', models.IntegerField(db_column='ID_Evento')),
            ],
            options={
                'db_table': 'usuario_evento',
                'unique_together': {('usuario_id', 'evento_id')},
            },
        ),
    ]
