# Generated by Django 4.2 on 2025-09-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioEvento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, db_column='Imagen', null=True, upload_to='eventos/'),
        ),
    ]
