# Generated by Django 4.2 on 2025-07-23 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='profesor',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='marcado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_marcadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
