# Generated by Django 4.2 on 2025-07-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_cursoprofesormateria_delete_cursoprofesor'),
        ('clases', '0003_remove_asistencia_estudiante_remove_clase_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='dictada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='personas.cursoprofesormateria'),
        ),
        migrations.AddField(
            model_name='clase',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clases.clase'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.DateField(),
        ),
    ]
