# Generated by Django 4.2 on 2025-07-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('clases', '0004_clase_dictada_por_clase_duracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='marcado_por',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='estudiantes.estudiante'),
        ),
    ]
