# Generated by Django 4.2 on 2025-08-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('clases', '0005_remove_asistencia_marcado_por_asistencia_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='asistencia_tomada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('clase', 'estudiante')},
        ),
    ]
