# Generated by Django 4.2 on 2025-08-31 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_cursoprofesormateria_delete_cursoprofesor'),
        ('estudiantes', '0001_initial'),
        ('clases', '0006_clase_asistencia_tomada_alter_asistencia_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='dictada_por',
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='cpm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='personas.cursoprofesormateria'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('cpm', 'estudiante', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['cpm', 'fecha'], name='asistencia_cpm_id_9b0093_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['estudiante', 'fecha'], name='asistencia_estudia_4eb0d8_idx'),
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='clase',
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
    ]
