# Generated by Django 4.2 on 2025-08-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_cursoprofesormateria_delete_cursoprofesor'),
        ('estudiantes', '0001_initial'),
        ('clases', '0007_remove_clase_dictada_por_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asistencia',
            name='asistencia_estudia_4eb0d8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('cpm', 'fecha', 'estudiante')},
        ),
    ]
