# Generated by Django 4.2 on 2025-09-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0008_remove_asistencia_asistencia_estudia_4eb0d8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('Presente', 'Presente'), ('Tarde', 'Tarde'), ('Ausente', 'Ausente')], max_length=8),
        ),
    ]
