# Generated by Django 4.2 on 2025-09-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='nivel_academico',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='estudiante_tipo_do_3b36a3_idx'),
        ),
    ]
