# Generated by Django 4.2 on 2025-09-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_remove_estudiante_nivel_academico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/estudiantes/'),
        ),
    ]
