# Generated by Django 4.2 on 2026-09-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_options_alter_curso_descripcion_and_more'),
        ('estudiantes', '0003_estudiante_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(help_text='Apellidos del estudiante', max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo_electronico',
            field=models.EmailField(blank=True, help_text='Correo institucional o de contacto del alumno', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(help_text='Curso o grado al que pertenece el estudiante', on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='cursos.curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(blank=True, help_text='Lugar de residencia familiar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento para cálculo de edad escolar', null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil del estudiante', null=True, upload_to='avatars/estudiantes/'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(help_text='Nombres del estudiante', max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de documento de identidad oficial', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto de emergencia', max_length=15, null=True),
        ),
    ]
