# Generated by Django 4.2 on 2026-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(help_text='Descripción pedagógica, objetivos o rango de edad del curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(help_text='Nombre del grado o curso (ej. Párvulos A)', max_length=100),
        ),
    ]
