# Generated by Django 4.2 on 2026-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(help_text='Nombre de la asignatura o área de aprendizaje', max_length=100),
        ),
    ]
