# Generated by Django 4.2 on 2025-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('personas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cursos',
            field=models.ManyToManyField(related_name='profesores', through='personas.CursoProfesor', to='cursos.curso'),
        ),
    ]
