# Generated by Django 4.2 on 2025-07-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        ('cursos', '0001_initial'),
        ('personas', '0004_remove_persona_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoProfesorMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_profesor', to='cursos.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_profesor', to='materias.materia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_profesor', to='personas.persona')),
            ],
            options={
                'db_table': 'curso_profesor_materia',
                'unique_together': {('persona', 'curso', 'materia')},
            },
        ),
        migrations.DeleteModel(
            name='CursoProfesor',
        ),
    ]
