# Generated by Django 4.2 on 2025-09-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_cursoprofesormateria_delete_cursoprofesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/personas/'),
        ),
    ]
