# Generated by Django 4.2 on 2026-09-23 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_options_alter_curso_descripcion_and_more'),
        ('estudiantes', '0004_alter_estudiante_apellido_and_more'),
        ('materias', '0002_alter_materia_options_alter_materia_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personas', '0006_persona_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoprofesormateria',
            name='curso',
            field=models.ForeignKey(help_text='Curso en el que se dicta la clase', on_delete=django.db.models.deletion.CASCADE, related_name='profesores_materia', to='cursos.curso'),
        ),
        migrations.AlterField(
            model_name='cursoprofesormateria',
            name='materia',
            field=models.ForeignKey(help_text='Materia asignada', on_delete=django.db.models.deletion.CASCADE, related_name='cursos_profesor', to='materias.materia'),
        ),
        migrations.AlterField(
            model_name='cursoprofesormateria',
            name='persona',
            field=models.ForeignKey(help_text='Docente asignado', on_delete=django.db.models.deletion.CASCADE, related_name='cursos_profesor', to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(help_text='Cuenta de usuario de acceso al sistema', on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personaestudiante',
            name='estudiante',
            field=models.ForeignKey(help_text='Estudiante a cargo', on_delete=django.db.models.deletion.CASCADE, related_name='acudientes_vinculados', to='estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='personaestudiante',
            name='parentesco',
            field=models.CharField(default='Acudiente', help_text='Vínculo familiar (Madre, Padre, etc.)', max_length=30),
        ),
        migrations.AlterField(
            model_name='personaestudiante',
            name='persona',
            field=models.ForeignKey(help_text='Acudiente responsable', on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_a_cargo', to='personas.persona'),
        ),
    ]
