# Generated by Django 4.2 on 2025-09-21 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0006_persona_foto'),
        ('estudiantes', '0003_estudiante_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('numero', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'periodo',
                'ordering': ['anio', 'numero'],
                'unique_together': {('anio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='NotaMateriaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.DecimalField(decimal_places=1, max_digits=3)),
                ('desempeño', models.CharField(blank=True, max_length=20)),
                ('inasistencias', models.PositiveSmallIntegerField(default=0)),
                ('observacion_docente', models.TextField(blank=True)),
                ('calculada', models.BooleanField(default=True)),
                ('cpm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.cursoprofesormateria')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodo')),
            ],
            options={
                'db_table': 'nota_materia_periodo',
                'unique_together': {('estudiante', 'cpm', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('cpm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='personas.cursoprofesormateria')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodo')),
            ],
            options={
                'db_table': 'logro',
                'ordering': ['cpm_id', 'periodo_id', 'orden'],
                'unique_together': {('cpm', 'periodo', 'orden')},
            },
        ),
    ]
