# Generated by Django 4.2 on 2025-07-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_actividad_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='profesor',
        ),
    ]
