# Generated by Django 4.2 on 2025-07-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_cursoprofesormateria_delete_cursoprofesor'),
        ('actividades', '0003_remove_actividad_curso_remove_actividad_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='asignada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='personas.cursoprofesormateria'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='actividad',
            table=None,
        ),
    ]
