# Generated by Django 4.2 on 2025-07-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actividad_asignada_por_alter_actividad_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actividad',
            table='actividad',
        ),
    ]
