# Generated by Django 4.2 on 2025-08-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_alter_actividad_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadestudiante',
            name='entrega',
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividadestudiante',
            name='entregado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividadestudiante',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
