# Generated by Django 4.2 on 2025-09-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_remove_actividadestudiante_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='entregable',
            field=models.FileField(blank=True, null=True, upload_to='entregables/'),
        ),
    ]
