# Generated by Django 4.2 on 2025-09-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_actividad_entregable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='entregable',
        ),
        migrations.AddField(
            model_name='actividadestudiante',
            name='entregable',
            field=models.FileField(blank=True, null=True, upload_to='entregables/'),
        ),
    ]
