# Generated by Django 4.2 on 2025-09-21 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_remove_actividad_entregable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadestudiante',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='actividades.actividad'),
        ),
    ]
