# Generated by Django 4.2 on 2025-09-21 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('actividades', '0009_alter_actividadestudiante_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.periodo'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
