# Generated by Django 4.2 on 2026-09-30 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_alter_cursoprofesormateria_curso_and_more'),
        ('academico', '0001_initial'),
        ('estudiantes', '0004_alter_estudiante_apellido_and_more'),
        ('actividades', '0010_actividad_periodo_actividad_peso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='asignada_por',
            field=models.ForeignKey(blank=True, help_text='Profesor, materia y curso que originan esta actividad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='personas.cursoprofesormateria'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(help_text='Instrucciones detalladas de la actividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(help_text='Fecha en que se asigna la actividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_entrega',
            field=models.DateField(blank=True, help_text='Fecha límite para la entrega de los estudiantes', null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='periodo',
            field=models.ForeignKey(blank=True, help_text='Período escolar al que suma esta calificación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.periodo'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje o peso ponderado de la actividad en la materia', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(help_text='Título de la tarea o evaluación', max_length=100),
        ),
        migrations.AlterField(
            model_name='actividadestudiante',
            name='actividad',
            field=models.ForeignKey(help_text='Actividad evaluada', on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='actividades.actividad'),
        ),
        migrations.AlterField(
            model_name='actividadestudiante',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Nivel de evaluación: 1 Deficiente, 2 Aceptable, 3 Sobresaliente', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='actividadestudiante',
            name='entregable',
            field=models.FileField(blank=True, help_text='Archivo de la tarea subido por el alumno o acudiente', null=True, upload_to='entregables/'),
        ),
        migrations.AlterField(
            model_name='actividadestudiante',
            name='entregado_en',
            field=models.DateTimeField(blank=True, help_text='Marca temporal de cuándo se realizó la entrega', null=True),
        ),
        migrations.AlterField(
            model_name='actividadestudiante',
            name='estudiante',
            field=models.ForeignKey(help_text='Estudiante evaluado', on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas', to='estudiantes.estudiante'),
        ),
    ]
